---

- name: "SECTION | 1.1.1.x | Disable unused filesystems"
  import_tasks: cis_1.1.1.x.yml

- name: "SECTION | 1.1.2.x | Configure /tmp"
  import_tasks: cis_1.1.2.x.yml

- name: "SECTION | 1.1.3.x | Configure /var"
  import_tasks: cis_1.1.3.x.yml

- name: "SECTION | 1.1.4.x | Configure /var/tmp"
  import_tasks: cis_1.1.4.x.yml

- name: "SECTION | 1.1.5.x | Configure /var/log"
  import_tasks: cis_1.1.5.x.yml

- name: "SECTION | 1.1.6.x | Configure /var/log/audit"
  import_tasks: cis_1.1.6.x.yml

- name: "SECTION | 1.1.7.x | Configure /home"
  import_tasks: cis_1.1.7.x.yml

- name: "SECTION | 1.1.8.x | Configure /dev/shm"
  import_tasks: cis_1.1.8.x.yml

- name: "SECTION | 1.1.x | Disable various mounting"
  import_tasks: cis_1.1.x.yml

- name: "SECTION | 1.2 | Configure Software Updates"
  import_tasks: cis_1.2.x.yml

- name: "SECTION | 1.3 | Filesystem Integrity Checking"
  import_tasks: cis_1.3.x.yml
  when: rhel8cis_config_aide

- name: "SECTION | 1.4 | Secure Boot Settings"
  import_tasks: cis_1.4.x.yml

- name: "SECTION | 1.5 | Additional Process Hardening"
  import_tasks: cis_1.5.x.yml

- name: "SECTION | 1.6 | Mandatory Access Control"
  import_tasks: cis_1.6.1.x.yml
  when: not rhel8cis_selinux_disable

- name: "SECTION | 1.7 | Command Line Warning Banners"
  import_tasks: cis_1.7.x.yml

- name: "SECTION | 1.8 | Gnome Display Manager"
  import_tasks: cis_1.8.x.yml

- name: "SECTION | 1.9 | Updates and Patches"
  import_tasks: cis_1.9.yml

- name: "SECTION | 1.10 | Crypto policies"
  import_tasks: cis_1.10.yml
  when:
  - not system_is_ec2

---

- name: "SECTION | 2.1 | Time Synchronization"
  import_tasks: cis_2.1.x.yml

- name: "SECTION | 2.2 | Special Purpose Services"
  import_tasks: cis_2.2.x.yml

- name: "SECTION | 2.3 | Service Clients"
  import_tasks: cis_2.3.x.yml

- name: "SECTION | 2.4 | Nonessential services removed"
  import_tasks: cis_2.4.yml

---

- name: "SECTION | 3.1.x | Disable unused network protocols and devices"
  import_tasks: cis_3.1.x.yml

- name: "SECTION | 3.2.x | Network Parameters (Host Only)"
  import_tasks: cis_3.2.x.yml

- name: "SECTION | 3.3.x | Network Parameters (Host and Router)"
  import_tasks: cis_3.3.x.yml

- name: "SECTION | 3.4.1.x | Configure firewalld"
  import_tasks: cis_3.4.1.x.yml
  when:
      - rhel8cis_firewall == "firewalld"

- name: "SECTION | 3.4.2.x | Configure nftables"
  import_tasks: cis_3.4.2.x.yml
  when:
      - rhel8cis_firewall == "nftables"

- name: "SECTION | 3.4.3.1.x | Configure iptables software"
  import_tasks: cis_3.4.3.1.x.yml
  when:
      - rhel8cis_firewall == "iptables"

- name: "SECTION | 3.4.3.2.x | Configure IPv4 iptables"
  import_tasks: cis_3.4.3.2.x.yml
  when:
      - rhel8cis_firewall == "iptables"

- name: "SECTION | 3.4.3.3.x | Configure IPv6 iptables"
  import_tasks: cis_3.4.3.3.x.yml
  when:
      - ( rhel8cis_firewall == "iptables" and rhel8cis_ipv6_required )

---

# 4.1 Configure System Accounting (auditd)
- name: "SECTION | 4.1| Ensure auditing is enabled"
  import_tasks: cis_4.1.1.x.yml
  when:
      - not system_is_container

- name: "SECTION | 4.1.2.x| Configure Data Retention"
  import_tasks: cis_4.1.2.x.yml

- name: "SECTION | 4.1.3.x| Configure auditd rules"
  import_tasks: cis_4.1.3.x.yml

# 4.2 Configure Logging
- name: "SECTION | 4.2.1.x| Configure rsyslog"
  import_tasks: cis_4.2.1.x.yml
  when: rhel8cis_syslog == 'rsyslog'

- name: "SECTION | 4.2.2.x| Configure journald"
  import_tasks: cis_4.2.2.x.yml
  when: rhel8cis_syslog == 'journald'

- name: "SECTION | 4.2.3 | Configure logile perms"
  import_tasks: cis_4.2.3.yml

- name: "SECTION | 4.3 | Configure logrotate"
  import_tasks: cis_4.3.yml

---

# Access, Authentication, and Authorization

- name: "SECTION | 5.1 | Configure time-based job schedulers"
  import_tasks: cis_5.1.x.yml

- name: "SECTION | 5.2 | Configure SSH Server"
  import_tasks: cis_5.2.x.yml
  when:
      - "'openssh-server' in ansible_facts.packages"

- name: "SECTION | 5.3 | Configure privilege escalation"
  import_tasks: cis_5.3.x.yml

- name: "SECTION | 5.4 | Configure authselect"
  import_tasks: cis_5.4.x.yml

- name: "SECTION | 5.5 | Configure PAM "
  import_tasks: cis_5.5.x.yml

- name: "SECTION | 5.6.1.x | Shadow Password Suite Parameters"
  import_tasks: cis_5.6.1.x.yml

- name: "SECTION | 5.6.x | Misc. User Account Settings"
  import_tasks: cis_5.6.x.yml

---

- name: "SECTION | 6.1 | System File Permissions"
  import_tasks: cis_6.1.x.yml

- name: "SECTION | 6.2 | User and Group Settings"
  import_tasks: cis_6.2.x.yml

